### ISSUE TITLE
На не людей могут действовать эффекты

### ISSUE THREAD

**Issue by lvvova1** [hnappinn/Barotrauma-Advanced-Medicine-mod#10]
HumanHusk может потерять пульс/кровь, изза чего уйти в оглушение, по идее на хасков это вообще не должно влиять.

Husk На него действует инфекция раны, т.к у существа нет имунитета

Crawler Получает артериальное кровотечение при том что обычное кровотечение затягивается мгновенно

Fractal Guardian 

Позже дополню как проверю вообще всех существ

**Comment by hnappinn** [comment]
У рапторов тоже затягивается кровотечения?

**Comment by hnappinn** [comment]
А кровь хаск теряет же и в ваниле

**Comment by lvvova1** [comment]
Дополняю:

Связи с тем что было выяснено как в афликшинах прописывать конкретных существ, необходимо запретить некоторым существам ловить эффекты которых у них по факту не должно быть

Fractalguardian, Fractalguardian2, Leucocyte, Terminalcell
Нужно исключить возможность удушья/артериальной кровопотери/переломов/заражённых ран/эффектов от вливания "не той крови"

Humanhusk, Husk
Исключить возможность удушья/артериальной кровопотери/заражённые раны/эффектов от вливания "не той крови"


К удушью я отношу: vt vf asys hypotension hypoxia traumaticshock
К заражению: septicwound necrosis infectedwound
Эффект вливания не той крови: hemotransfusionshock
Перелом: fracture
Артериальное: arterialcut
