### ISSUE TITLE
Скальпель можно использовать без морфия

### ISSUE THREAD

**Issue by lvvova1** [hnappinn/Barotrauma-Advanced-Medicine-mod#3]
Нашёл баг:

- Скальпель можно использовать без морфия. 
- Скорее всего срабатывает в случае неудачной попытки использовать скальпель.
- Срабатывает только если на теле нет надрезов.

**Comment by hnappinn** [comment]
Да, забыл что надрез при ошибке тоже появляется. Исправим

**Comment by hnappinn** [comment]
А, не. Проблема была еще в другом, но во всяком случае я теперь исправил
