### ISSUE TITLE
Fix Ambu bag

### ISSUE THREAD

**Issue by lvvova1** [hnappinn/Barotrauma-Advanced-Medicine-mod#35]
Need fix scale, hands

**Comment by lvvova1** [comment]
Also ambu bag have issue, if use it when patient have Hypotension and use ambu bag to recover oxygen, patient wake up but through hypotension he again falls

**Comment by lvvova1** [comment]
Fixed scale https://github.com/hnappinn/Barotrauma-Advanced-Medicine-mod/pull/36/commits/85820468d216c365d2026c0440dda72c38cc7675

**Comment by Zargserg** [comment]
Can you tell me at which hypotension level this is happening?
Also: That might not be a bug as hypotension means blood is less effectively pumped through the body thus there might not be enough oxygen going through your brain leading to unconsciousness (Especially if blood pressure drops dangerously low).
