### ISSUE TITLE
Балансные правки

### ISSUE THREAD

**Issue by lvvova1** [hnappinn/Barotrauma-Advanced-Medicine-mod#9]
1. Хирургические швы: 
Стоит удешевить крафт: 0.5/0.25 алюминия будет достаточно я думаю(т.к на начальных этапах с алюминием всегда беда)
Добавить возможность "объеденять" швы(Как сейчас можно с балонами например)

2. Маннит
Он слишком дорогой, предлагаю удешевить крафт:
"Спирт, Углерод, Стабилоцин, Физраствор"(Можно и без Стабилоцина) https://www.gastroscan.ru/handbook/144/5423
Или альтернативы:
1 "Стабилоцин, Кислорит" 2. "Стабилоцин, Адреналин" 3. "Адреналин, Кислорит"
Кроме того что есть выше добавить, спирт/углерод

3. Удешевить крафт инструментов,
Если сталь ещё ладно но цинк я думаю стоит на 0,5 выставить.
(Для скальпеля, advhemostat, advretractors, tweezers, для дрели оставить как есть)

4. Слышал ещё жалобу на то что человека слишком долго нужно откачивать
В принципе с ней согласен, человека действительно слишком долго откачивать, но тут уже на твоё усмотрение

**Comment by hnappinn** [comment]
1. Сделаю
2. Я вообще хотел придумать название похожее на Маннитол, но выдуманное. Потому что в настоящее время нету никаких препаратов что лечат гипоксию мозга. Хотя... можно просто назвать Маннитол+. Рецепт сделаю чуть проще.
3. Инструменты из нержавейки и по этому они многоразовые. Сделаю 0.5
4. Я изменю в будущем физраствор чтобы он поднимал давление, и защищал от асистолии при кровопотери

**Comment by hnappinn** [comment]
1, 2 и 3 готово
